version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Usa una imagen con Python preinstalado

    working_directory: ~/my-project

    steps:
      - checkout

      # Ejecutar el script de Python
      - run:
          name: Ejecutar math_operations.py
          command: |
            python math_operations.py

workflows:
  build-deploy:
    jobs:
      - build
