version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Imagen base para Python
      - image: circleci/postgres:11  # Añadir PostgreSQL como servicio

    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run:
          name: Create user and database
          command: |
            psql -U postgres -c "CREATE USER ubuntu WITH SUPERUSER;"
            psql -U postgres -c "CREATE DATABASE test_db;"
      - run:
          name: Run tests
          command: |
            python -m unittest discover
