version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Usa una imagen con Python preinstalado

    working_directory: ~/my-project

    steps:
      - checkout

      # Instalar dependencias si es necesario (en este caso no hay ninguna)
      - run:
          name: Ejecutar Hola Mundo
          command: |
            echo 'print("Hola Mundo")' > hola_mundo.py
            python hola_mundo.py

workflows:
  build-deploy:
    jobs:
      - build
